# Generated by Django 3.0.6 on 2020-06-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
